site_name: 'baudisgroup @ UZH & SIB'
site_description: 'Computational Oncogenomics Group @ UZH & SIB'
site_author: Michael Baudis
copyright: '&copy; Copyright 2007 - 2025 Michael Baudis'
repo_name: 'baudisgroup.github.io'

repo_url: https://github.com/baudisgroup/baudisgroup.github.io
edit_uri: edit/main/docs/

###############################################################################

nav:
  - 'Baudisgroup Home': https://baudisgroup.org
  - Address: https://baudisgroup.org/address
  - Group Members: https://baudisgroup.org/group
  - Publications: https://baudisgroup.org/publications
  - Presentations: https://baudisgroup.org/presentations
  - Projects and Open Positions: https://baudisgroup.org/projects-and-positions
  - 'Teaching and Seminars':
    - 'BIO390 Lectures &#8599;': https://compbiozurich.org/teaching/UZH-BIO390/
    - 'BIO392 Block Course &#8599;': https://compbiozurich.org/teaching/UZH-BIO392/
    - 'ZH Bioinfo Seminars &#8599;': https://compbiozurich.org/news/
  - 'Progenetix &#8599;': http://progenetix.org
  - 'Cancercelllines &#8599;': http://cancercelllines.org
  - 'CompbioZurich &#8599;': https://compbiozurich.org
  - 'SchemaBlocks {S}[B] &#8599;': https://schemablocks.org
  - Beacon Project &#8599;: https://beacon-project.io
  - Michael Baudis @ UZH &#8599;: https://www.mls.uzh.ch/en/research/baudis.html

###############################################################################

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.saneheaders
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - mdx_gh_links:
      user: hCNV
      repo: hcnv.github.io

###############################################################################

theme:
  name: material
  palette:
    primary: white
    accent: white
  favicon: img/favicon.ico
  logo: img/site_logo.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
  custom_dir: extras
      
plugins:
    - search
    # - with-pdf:
    #     author: Progenetix
    #     output_path: pdf/progenetix-documentation.pdf
    # - macros
    # - mermaid2

extra:
  excerpt_separator: <!--more-->
  blog_list_length: 100
  news:
    dir: news
  presentations:
    dir: presentations
  publications:
    dir: publications
  contacts:
    dir: group
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/baudisgroup
extra_css:
  - css/theme_overrides.css
    
