site_name: 'baudisgroup @ UZH & SIB'
site_description: 'Computational Oncogenomics Group @ UZH & SIB'
site_author: Michael Baudis
copyright: '&copy; Copyright 2007 - 2022 Michael Baudis'
repo_name: 'baudisgroup.github.io'

repo_url: https://github.com/baudisgroup/baudisgroup.github.io
edit_uri: edit/main/docs/

###############################################################################

nav:
  - 'Baudisgroup Home': index.md
  - Group: group
  - Publications: publications
  - Presentations: presentations
  - 'SchemaBlocks {S}[B] &#8599;': https://schemablocks.org
  - Beacon Project &#8599;: https://beacon-project.io
  - Michael Baudis @ UZH &#8599;: https://www.mls.uzh.ch/en/research/baudis.html

###############################################################################

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.saneheaders
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:mermaid2.fence_mermaid   
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - mdx_gh_links:
      user: hCNV
      repo: hcnv.github.io
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
          custom_icons:
            - mkdocs_overrides/.icons

###############################################################################

theme:
  name: material
  palette:
    primary: light blue
    accent: indigo
  # favicon: img/logo-schemablocks-no-text-50x50.png
  # logo: img/logo-GA4GH-white-text-670x160.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
  custom_dir: mkdocs_overrides
      
plugins:
    - search
    # - with-pdf:
    #     author: Progenetix
    #     output_path: pdf/progenetix-documentation.pdf
    # - macros
    # - mermaid2

extra:
  excerpt_separator: <!--more-->
  blog_list_length: 50
  news:
    dir: news
    extended_preview: true
  presentations:
    dir: presentations
    extended_preview: true
  publications:
    dir: publications
    extended_preview: true
  contacts:
    dir: group
    extended_preview: true
  social:
    # - icon: fontawesome/brands/twitter 
    #   link: https://twitter.com/progenetix
    - icon: fontawesome/brands/github 
      link: https://github.com/baudisgroup
extra_css:
  - css/theme_overrides.css
# extra_javascript:
  # - https://unpkg.com/mermaid/dist/mermaid.min.js
  # - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
    
